apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: grpc-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: grpc
        protocol: GRPC
      hosts:
        - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grpc-virtualservice
spec:
  hosts:
    - "*"
  gateways:
    - grpc-gateway
  http:
    - match:
        - uri:
            prefix: / # adjust based on your gRPC endpoint
      route:
        - destination:
            host: grpc-server
            port:
              number: 8080

