apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server-deployment
  labels:
    app: go-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
      - name: go-server
        image: application-go:latest # ここをあなたのDockerイメージに置き換えてください
        imagePullPolicy: Never
        ports:
        - containerPort: 8080 # Goサーバーがリッスンしているポート
---

apiVersion: v1
kind: Service
metadata:
  name: go-server-service
spec:
  selector:
    app: go-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
